Docs: Initial Content for Sumo Logic
aws-samples/aws-modernization-with-sumologic pull request #1
Opened 2021-11-23 22:29 UTC by lorikrell

*Issue #, if available:*
None at this time

*Description of changes:*
Created initial content for Sumo Logic including:

- Intro updates for Sumo Logic, new logo for badge
- Self Guided added new page for Sumo Logic
- Added folder and content for Observability and Monitoring Labs - 2 labs, with scenario intro
- Cleanup info about the lab environment
- README updated to help Sumo writers continue to contribute

I noticed the intro for Self Guided mentions IAM setup, but the repo and original repo with the base didn't have those files. Also need a Survey link.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-11-23 23:44 UTC, dilipmrajan9 commented on README.md
> +title: "Observability and Monitoring Lab"
Can we please include "AWS" in front of Observability?

2021-11-23 23:53 UTC, dilipmrajan9 commented on content/040_observability_monitoring_lab/40_scenario.md
> +- ELB (Application Load Balancer)
Can we expand ELB? And prefix with Amazon

2021-11-23 23:54 UTC, dilipmrajan9 commented on content/040_observability_monitoring_lab/40_scenario.md
> +- Host/EC2
Expand EC2 ( Amazon Elastic Compute Cloud). Required for the first reference, further mentions of the service can be abbreviated.

2021-11-23 23:55 UTC, dilipmrajan9 commented on content/040_observability_monitoring_lab/40_scenario.md
> +- DynamoDB
Amazon DynamoDB

2021-11-23 23:55 UTC, dilipmrajan9 commented on content/040_observability_monitoring_lab/40_scenario.md
> +The TravelLogic app faces unusual latency in loading the app web page, also sometimes resulting in outage in the us-area-1. You need to find out the root cause of the latency and outages ASAP.
as soon as possible

2021-11-23 23:56 UTC, dilipmrajan9 commented on content/040_observability_monitoring_lab/42_lab1.md
> +The TravelLogic app that you support faces unusual latency in loading the app web page, also sometimes resulting in outage in the us-area-1. You need to find out the root cause of the latency and out
us-area-1 might be difficult for audience to understand. Can we say us-east-1? ASAP - as soon as possible.

2021-11-23 23:58 UTC, dilipmrajan9 commented on content/040_observability_monitoring_lab/42_lab1.md
> +    ![AWS DynamoDB Events](/images/lab-monitoring/lab1-dynamodb-events.png)
Only first reference of the service name needs to be "AWS" + Service name. So can remove AWS reference for future references. Pls update rest of the docs with the same.

2021-11-24 00:15 UTC, dilipmrajan9 requested changes
Hi Lori - Overall looks good but i have made some suggestions for AWS service naming protocol. Could you please make those changes and I can go ahead and merge?

2021-11-24 16:46 UTC, lorikrell commented
Updated, thank you for the review feedback! I also did global searches for some of those items like ASAP, etc.

2021-11-24 17:13 UTC, merged